[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
tokio = { workspace = true }
serde_json = { workspace = true }
derive_more = { workspace = true }
async-channel = { workspace = true }
